# Generated by Django 5.1.5 on 2025-02-12 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('max_takeoff_weight', models.FloatField()),
                ('max_flight_speed', models.FloatField()),
                ('current_status', models.CharField(choices=[('in_stock', '在库'), ('in_flight', '飞行中'), ('maintenance', '维修中')], default='in_stock', max_length=20)),
                ('total_flight_time', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drone',
            },
        ),
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_date', models.DateTimeField()),
                ('takeoff_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('emergency_record', models.TextField(blank=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones.drone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flight records',
            },
        ),
    ]
