# Generated by Django 5.1.5 on 2025-03-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='current_load',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flightrecord',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods'),
        ),
    ]
