# Generated by Django 5.1.5 on 2025-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_drone_current_load_flightrecord_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
