# Generated by Django 5.1.5 on 2025-06-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_drone_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
