# Generated by Django 5.2.4 on 2025-07-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_alter_drone_serial_number_droneposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='endurance_time',
            field=models.IntegerField(default=0),
        ),
    ]
