# Generated by Django 5.2.4 on 2025-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_drone_endurance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
