# Generated by Django 5.2.4 on 2025-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0007_drone_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='task_id',
        ),
        migrations.AddField(
            model_name='droneposition',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
