# Generated by Django 5.1.5 on 2025-08-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0008_remove_drone_task_id_droneposition_task_id'),
    ]

    operations = [
    ]
