# Generated by Django 5.1.5 on 2025-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0009_auto_20250825_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='flight_time',
            field=models.IntegerField(default=0),
        ),
    ]
