# Generated by Django 5.1.5 on 2025-08-26 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0010_drone_flight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='endurance_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='续航时间必须大于0')]),
        ),
        migrations.AlterField(
            model_name='drone',
            name='max_flight_speed',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='最大飞行速度必须大于0')]),
        ),
        migrations.AlterField(
            model_name='drone',
            name='max_takeoff_weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='最大起飞重量必须大于0')]),
        ),
    ]
