# Generated by Django 5.1.5 on 2025-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=15)),
                ('sender_address', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', '待发货'), ('in_transit', '运输中'), ('delivered', '已送达'), ('issue', '问题件')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
