# Generated by Django 5.1.5 on 2025-03-24 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_drone_goods_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='drone_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default='未命名货物', max_length=255),
        ),
        migrations.AlterField(
            model_name='goods',
            name='volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
