# Generated by Django 5.1.5 on 2025-03-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_drone_current_load_flightrecord_goods'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goods', to='drones.drone'),
        ),
        migrations.AddField(
            model_name='goods',
            name='scheduled_time',
            field=models.DateTimeField(null=True),
        ),
    ]
