# Generated by Django 5.1.5 on 2025-07-05 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_receiver_name_goods_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
