# Generated by Django 5.1.5 on 2025-08-26 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_created_at_goods_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='volume',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001, message='体积必须大于0')]),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='重量必须大于0')]),
        ),
    ]
